### ISSUE TITLE
An issue about yolo.weight

### ISSUE THREAD

**Issue by lisaner000** [sxl142/GLoT#14]
I have a question about yolo.weight you provided. 
Traceback (most recent call last):
  File "demo.py", line 382, in <module>
    main(args, cfgs)
  File "demo.py", line 78, in main
    yolo_img_size=args.yolo_img_size,
  File "/root/miniconda3/envs/glot/lib/python3.7/site-packages/multi_person_tracker/mpt.py", line 53, in __init__
    device=self.device, img_size=yolo_img_size, person_detector=True, video=True, return_dict=True
  File "/root/miniconda3/envs/glot/lib/python3.7/site-packages/yolov3/yolo.py", line 51, in __init__
    self.model.load_darknet_weights(weights_path)
  File "/root/miniconda3/envs/glot/lib/python3.7/site-packages/yolov3/models.py", line 315, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[512, 256, 3, 3]' is invalid for input of size 971393

**Comment by sxl142** [comment]
Please check your Python environment, and ensure that it is aligned with our provided.
